[package]
name = "async-std-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-std = { version = "1.12.0", features = ["async-attributes", "async-process", "attributes", "futures-core", ] }
surf = "2.3.2"
