appenders:
  console:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%s)(utc)} [{f}:{L}] - {h({l})}: {M}:{m}{n}"
  file:
    kind: rolling_file
    path: "logs/current-supervisor.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%s)(utc)} [{f}:{L}] - {h({l})}: {M}:{m}{n}"
    policy:
      trigger:
        kind: size
        limit: 250kb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "log/rolled-supervisor.{}.log"
root:
  level: info
  appenders:
    - console
    - file
