
name = "redis-supervisor"
version = "0.1.4"
base_port = 0 # set to zero to use domain socket connection
instance_folder = "instances"
instance_count = 3
redis_template = "config/redis.conf-socket.template"
startup_delay_seconds = 2
ping_loop_interval_seconds = 5
ping_loop_limit = 10
