alias t := test
alias ta := test-all
alias b := build
alias rel := release

# run the standard tests
test:
    clear
    cargo test

# run the standard tests + clippy and fmt
test-all:
    clear
    cargo test && cargo fmt && cargo clippy

# build the debug target
build:
    clear
    cargo build

# build the docs
docs:
    cargo doc --no-deps --open

# run the debug app
run:
    cargo run -- --flight-plan plans/test-plan.json

# build the release
release:
    clear
    cargo build --release && clear && ./target/release/spacial_controller --help

# watch the current folders and run tests when a file is changed
watch:
    watchexec -d 500 -c -e rs cargo test

# merge the develop branch to main
merge:
    git push && git checkout main && git pull && git merge develop && git push && git checkout develop

pull-piedmont:
    ssh dpw@piedmont 'cd ~/raincity/rust-projects/spacial-controller && git pull'

pull-tiburon:
    ssh dpw@tiburon 'cd ~/raincity/rust-projects/spacial-controller && git pull'

pull-remotes:
    just pull-piedmont
    just pull-tiburon
