alias t := test
alias ta := test-all
alias b := build
alias rel := release

mkcert:
    openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365 -subj "/C=US/ST=California/L=Berkeley/O=RainCitySoftware/CN=raincitysoftware.com"

# run the standard tests
test:
    clear
    cargo test

# run the standard tests + clippy and fmt
test-all:
    clear
    cargo test && cargo fmt && cargo clippy

# build the debug target
build:
    clear
    cargo build

# build the docs
docs:
    cargo doc --no-deps --open

# run the debug app
run:
    clear && cargo run

# build the release
release:
    clear
    cargo build --release && clear && cargo run --release

# watch the current folders and run tests when a file is changed
watch:
    watchexec -d 500 -c -e rs just test-all

