
alias t := test
alias ta := test-all
alias b := build
alias rel := release

# run the standard tests
test:
    clear
    cargo test

# run the standard tests + clippy and fmt
test-all:
    clear
    cargo test && cargo fmt && cargo clippy

# build the debug target
build:
    clear
    cargo build

# run the default bin
run:
    cargo run

# build the release
release:
    clear
    cargo build --release

