[package]
name = "age-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = { version = "0.9.0", features = ["armor", "aes", "ssh", "rsa", "bcrypt-pbkdf"] }
anyhow = "1.0.66"
clap = "4.0.29"
