
alias b := build
alias t := test
alias ta := test-all

# run the standard tests
test:
    clear
    cargo test

# run the standard tests + clippy and fmt
test-all:
    clear
    cargo test && cargo fmt && cargo clippy

# build the debug target
build:
    clear
    cargo build

async-process:
    cargo run --bin async-process

fastrand:
    cargo run --bin fastrand-test

chacha:
    cargo run --bin chacha-test

b64:
    cargo run --bin base64-safe -- 'this is a test string with rtkey: 0VdX7fJnEfp6Kd0H'

rel:
    cargo build --release --bins
