
alias b := build
alias t := test
alias ta := test-all

# run the standard tests
test:
    clear
    cargo test && cargo clippy

# run the standard tests + clippy and fmt
test-all:
    clear
    cargo test && cargo fmt && cargo clippy

# build the debug target
build:
    clear
    cargo build

ts2date:
    cargo build --bin ts2date && date "+%s" | xargs ./target/debug/ts2date

tree-struct:
    cargo build --bin tree-struct && ./target/debug/tree-struct

runner:
    cargo build --bin runner && ./target/debug/runner

stdin-mock:
    cargo run --bin stdin-mock

http-client:
    cargo run --bin http-client

udp-service:
    cargo run --bin udp-service

exithook:
    cargo run --bin exit-hook

bin-ser-des:
    cargo run --bin bin-ser-des

socket-service:
    cargo run --bin socket-service

socket-client:
    cargo run --bin socket-client

thread-map:
    cargo run --bin thread-map

async-process:
    cargo run --bin async-process

fastrand:
    cargo run --bin fastrand-test

# run chacha
chacha:
    cargo run --bin chacha -- --help

# filewalk
filewalk:
    cargo run --bin file-walk

# run factors for a single number
factors:
    cargo run --bin factors -- 24

b64:
    cargo run --bin base64-safe -- 'this is a test string with rtkey: 0VdX7fJnEfp6Kd0H'

b85:
    cargo run --bin base85-std -- 'this is a test string with rtkey: 0VdX7fJnEfp6Kd0H'

timeops:
    cargo run --bin time_ops

# release all the bins
rel:
    cargo build --release --bins
