
alias b := build
alias t := test
alias ta := test-all

# run the standard tests
test:
    clear
    cargo test

# run the standard tests + clippy and fmt
test-all:
    clear
    cargo test && cargo fmt && cargo clippy

# build the debug target
build:
    clear
    cargo build

async-process:
    cargo run --bin async-process

fastrand:
    cargo run --bin fastrand-test

# run chacha
chacha:
    cargo run --bin chacha -- --help

# run factors for a single number
factors:
    cargo run --bin factors -- 24

b64:
    cargo run --bin base64-safe -- 'this is a test string with rtkey: 0VdX7fJnEfp6Kd0H'

b85:
    cargo run --bin base85-std -- 'this is a test string with rtkey: 0VdX7fJnEfp6Kd0H'

timeops:
    cargo run --bin time_ops

rel:
    cargo build --release --bins
