[package]
name = "openssl-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.8.0"
openssl = "0.10.42"
openssl-sys = "0.9.77"
